2012-11-28 16:21:21+0200 [-] Log opened.
2012-11-28 16:21:21+0200 [-] twistd 12.2.0 (/home/durand/projects/smk/products/dnssystem/site/venv/bin/python2.7 2.7.3) starting up.
2012-11-28 16:21:21+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2012-11-28 16:21:21+0200 [-] Traceback (most recent call last):
2012-11-28 16:21:21+0200 [-]   File "/home/durand/projects/smk/products/dnssystem/site/venv/bin/twistd", line 14, in <module>
2012-11-28 16:21:21+0200 [-]     run()
2012-11-28 16:21:21+0200 [-]   File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 27, in run
2012-11-28 16:21:22+0200 [-]     app.run(runApp, ServerOptions)
2012-11-28 16:21:22+0200 [-]   File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/application/app.py", line 652, in run
2012-11-28 16:21:22+0200 [-]     runApp(config)
2012-11-28 16:21:22+0200 [-]   File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 23, in runApp
2012-11-28 16:21:22+0200 [-]     _SomeApplicationRunner(config).run()
2012-11-28 16:21:22+0200 [-]   File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/application/app.py", line 390, in run
2012-11-28 16:21:22+0200 [-]     self.postApplication()
2012-11-28 16:21:22+0200 [-]   File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/scripts/_twistd_unix.py", line 230, in postApplication
2012-11-28 16:21:22+0200 [-]     self.startApplication(self.application)
2012-11-28 16:21:22+0200 [-]   File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/scripts/_twistd_unix.py", line 340, in startApplication
2012-11-28 16:21:22+0200 [-]     service.IService(application).privilegedStartService()
2012-11-28 16:21:22+0200 [-]   File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/application/service.py", line 277, in privilegedStartService
2012-11-28 16:21:22+0200 [-]     service.privilegedStartService()
2012-11-28 16:21:22+0200 [-]   File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/application/service.py", line 277, in privilegedStartService
2012-11-28 16:21:22+0200 [-]     service.privilegedStartService()
2012-11-28 16:21:22+0200 [-]   File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/application/internet.py", line 105, in privilegedStartService
2012-11-28 16:21:22+0200 [-]     self._port = self._getPort()
2012-11-28 16:21:22+0200 [-]   File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/application/internet.py", line 133, in _getPort
2012-11-28 16:21:22+0200 [-]     'listen%s' % (self.method,))(*self.args, **self.kwargs)
2012-11-28 16:21:22+0200 [-]   File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 476, in listenTCP
2012-11-28 16:21:22+0200 [-]     p.startListening()
2012-11-28 16:21:22+0200 [-]   File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/tcp.py", line 969, in startListening
2012-11-28 16:21:22+0200 [-]     raise CannotListenError, (self.interface, self.port, le)
2012-11-28 16:21:22+0200 [-] twisted.internet.error.CannotListenError: Couldn't listen on any:53: [Errno 13] Permission denied.
2012-11-28 16:21:47+0200 [-] Log opened.
2012-11-28 16:21:47+0200 [-] twistd 12.2.0 (/home/durand/projects/smk/products/dnssystem/site/venv/bin/python2.7 2.7.3) starting up.
2012-11-28 16:21:47+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2012-11-28 16:21:47+0200 [-] DNSServerFactory starting on 53000
2012-11-28 16:21:47+0200 [-] DNSDatagramProtocol starting on 53000
2012-11-28 16:21:47+0200 [-] failed to set uid/gid 1/1 (are you root?) -- exiting.
2012-11-28 16:21:49+0200 [-] Log opened.
2012-11-28 16:21:49+0200 [-] twistd 12.2.0 (/home/durand/projects/smk/products/dnssystem/site/venv/bin/python2.7 2.7.3) starting up.
2012-11-28 16:21:49+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2012-11-28 16:21:49+0200 [-] DNSServerFactory starting on 53000
2012-11-28 16:21:49+0200 [-] DNSDatagramProtocol starting on 53000
2012-11-28 16:21:49+0200 [-] failed to set uid/gid 1/1 (are you root?) -- exiting.
2012-11-28 16:25:24+0200 [-] Log opened.
2012-11-28 16:25:24+0200 [-] twistd 12.2.0 (/home/durand/projects/smk/products/dnssystem/site/venv/bin/python2.7 2.7.3) starting up.
2012-11-28 16:25:24+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2012-11-28 16:25:24+0200 [-] DNSServerFactory starting on 53000
2012-11-28 16:25:24+0200 [-] DNSDatagramProtocol starting on 53000
2012-11-28 16:32:48+0200 [-] Received SIGTERM, shutting down.
2012-11-28 16:32:48+0200 [-] (UDP Port 53000 Closed)
2012-11-28 16:32:48+0200 [-] (TCP Port 53000 Closed)
2012-11-28 16:32:48+0200 [-] Main loop terminated.
2012-11-28 16:32:48+0200 [-] Server Shut Down.
2012-11-28 16:54:01+0200 [-] Log opened.
2012-11-28 16:54:01+0200 [-] twistd 12.2.0 (/home/durand/projects/smk/products/dnssystem/site/venv/bin/python2.7 2.7.3) starting up.
2012-11-28 16:54:01+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2012-11-28 16:54:01+0200 [-] DNSServerFactory starting on 53000
2012-11-28 16:54:01+0200 [-] DNSDatagramProtocol starting on 53000
2012-11-28 16:54:01+0200 [-] /home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/python/util.py:713: exceptions.UserWarning: tried to drop privileges and setuid 1000 but uid is already 1000; should we be root? Continuing.
2012-11-28 16:54:01+0200 [-] set uid/gid 1000/100
2012-11-28 16:58:04+0200 [DNSDatagramProtocol (UDP)] Unhandled Error
	Traceback (most recent call last):
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 68, in lookupAddress
	    return self._lookup(name, dns.IN, dns.A, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 48, in _lookup
	    FailureHandler(r.query, q, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 312, in addErrback
	    errbackKeywords=kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 290, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 551, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 29, in __call__
	    return self.resolver(self.query, self.timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 57, in query
	    return self.typeToMethod[query.type](str(query.name), timeout)
	  File "./server.py", line 33, in lookupAddress
	    return super( MapResolver, lookupAddress ).lookupAddress( name, timeout )
	exceptions.NameError: global name 'lookupAddress' is not defined
	
2012-11-28 16:58:11+0200 [DNSDatagramProtocol (UDP)] Unhandled Error
	Traceback (most recent call last):
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 68, in lookupAddress
	    return self._lookup(name, dns.IN, dns.A, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 48, in _lookup
	    FailureHandler(r.query, q, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 312, in addErrback
	    errbackKeywords=kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 290, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 551, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 29, in __call__
	    return self.resolver(self.query, self.timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 57, in query
	    return self.typeToMethod[query.type](str(query.name), timeout)
	  File "./server.py", line 33, in lookupAddress
	    return super( MapResolver, lookupAddress ).lookupAddress( name, timeout )
	exceptions.NameError: global name 'lookupAddress' is not defined
	
2012-11-28 16:58:17+0200 [DNSDatagramProtocol (UDP)] Unhandled Error
	Traceback (most recent call last):
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 68, in lookupAddress
	    return self._lookup(name, dns.IN, dns.A, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 48, in _lookup
	    FailureHandler(r.query, q, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 312, in addErrback
	    errbackKeywords=kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 290, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 551, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 29, in __call__
	    return self.resolver(self.query, self.timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 57, in query
	    return self.typeToMethod[query.type](str(query.name), timeout)
	  File "./server.py", line 33, in lookupAddress
	    return super( MapResolver, lookupAddress ).lookupAddress( name, timeout )
	exceptions.NameError: global name 'lookupAddress' is not defined
	
2012-11-28 16:59:01+0200 [DNSDatagramProtocol (UDP)] Unhandled Error
	Traceback (most recent call last):
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 68, in lookupAddress
	    return self._lookup(name, dns.IN, dns.A, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 48, in _lookup
	    FailureHandler(r.query, q, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 312, in addErrback
	    errbackKeywords=kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 290, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 551, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 29, in __call__
	    return self.resolver(self.query, self.timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 57, in query
	    return self.typeToMethod[query.type](str(query.name), timeout)
	  File "./server.py", line 33, in lookupAddress
	    return super( MapResolver, lookupAddress ).lookupAddress( name, timeout )
	exceptions.NameError: global name 'lookupAddress' is not defined
	
2012-11-28 16:59:15+0200 [-] Received SIGTERM, shutting down.
2012-11-28 16:59:15+0200 [-] (UDP Port 53000 Closed)
2012-11-28 16:59:15+0200 [-] (TCP Port 53000 Closed)
2012-11-28 16:59:15+0200 [-] Main loop terminated.
2012-11-28 16:59:15+0200 [-] Server Shut Down.
2012-11-28 16:59:22+0200 [-] Log opened.
2012-11-28 16:59:22+0200 [-] twistd 12.2.0 (/home/durand/projects/smk/products/dnssystem/site/venv/bin/python2.7 2.7.3) starting up.
2012-11-28 16:59:22+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2012-11-28 16:59:22+0200 [-] DNSServerFactory starting on 53000
2012-11-28 16:59:22+0200 [-] DNSDatagramProtocol starting on 53000
2012-11-28 16:59:22+0200 [-] /home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/python/util.py:713: exceptions.UserWarning: tried to drop privileges and setuid 1000 but uid is already 1000; should we be root? Continuing.
2012-11-28 16:59:22+0200 [-] set uid/gid 1000/100
2012-11-28 16:59:25+0200 [DNSDatagramProtocol (UDP)] Unhandled Error
	Traceback (most recent call last):
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 68, in lookupAddress
	    return self._lookup(name, dns.IN, dns.A, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 48, in _lookup
	    FailureHandler(r.query, q, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 312, in addErrback
	    errbackKeywords=kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 290, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 551, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 29, in __call__
	    return self.resolver(self.query, self.timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 57, in query
	    return self.typeToMethod[query.type](str(query.name), timeout)
	  File "./server.py", line 33, in lookupAddress
	    return super( MapResolver, self ).lookupAddress( name, timeout )
	exceptions.TypeError: must be type, not classobj
	
2012-11-28 17:03:43+0200 [-] Received SIGTERM, shutting down.
2012-11-28 17:03:43+0200 [-] (UDP Port 53000 Closed)
2012-11-28 17:03:43+0200 [-] (TCP Port 53000 Closed)
2012-11-28 17:03:43+0200 [-] Main loop terminated.
2012-11-28 17:03:43+0200 [-] Server Shut Down.
2012-11-28 17:03:45+0200 [-] Log opened.
2012-11-28 17:03:45+0200 [-] twistd 12.2.0 (/home/durand/projects/smk/products/dnssystem/site/venv/bin/python2.7 2.7.3) starting up.
2012-11-28 17:03:45+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2012-11-28 17:03:45+0200 [-] DNSServerFactory starting on 53000
2012-11-28 17:03:45+0200 [-] DNSDatagramProtocol starting on 53000
2012-11-28 17:03:45+0200 [-] /home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/python/util.py:713: exceptions.UserWarning: tried to drop privileges and setuid 1000 but uid is already 1000; should we be root? Continuing.
2012-11-28 17:03:45+0200 [-] set uid/gid 1000/100
2012-11-28 17:03:51+0200 [DNSDatagramProtocol (UDP)] Unhandled Error
	Traceback (most recent call last):
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 68, in lookupAddress
	    return self._lookup(name, dns.IN, dns.A, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 48, in _lookup
	    FailureHandler(r.query, q, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 312, in addErrback
	    errbackKeywords=kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 290, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 551, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 29, in __call__
	    return self.resolver(self.query, self.timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 57, in query
	    return self.typeToMethod[query.type](str(query.name), timeout)
	  File "./server.py", line 33, in lookupAddress
	    return super( self, MapResolver ).lookupAddress( name, timeout )
	exceptions.TypeError: must be type, not instance
	
2012-11-28 17:03:54+0200 [DNSDatagramProtocol (UDP)] Unhandled Error
	Traceback (most recent call last):
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 68, in lookupAddress
	    return self._lookup(name, dns.IN, dns.A, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 48, in _lookup
	    FailureHandler(r.query, q, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 312, in addErrback
	    errbackKeywords=kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 290, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 551, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 29, in __call__
	    return self.resolver(self.query, self.timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 57, in query
	    return self.typeToMethod[query.type](str(query.name), timeout)
	  File "./server.py", line 33, in lookupAddress
	    return super( self, MapResolver ).lookupAddress( name, timeout )
	exceptions.TypeError: must be type, not instance
	
2012-11-28 17:10:25+0200 [-] Received SIGTERM, shutting down.
2012-11-28 17:10:25+0200 [-] (UDP Port 53000 Closed)
2012-11-28 17:10:25+0200 [-] (TCP Port 53000 Closed)
2012-11-28 17:10:25+0200 [-] Main loop terminated.
2012-11-28 17:10:25+0200 [-] Server Shut Down.
2012-11-28 17:10:51+0200 [-] Log opened.
2012-11-28 17:10:51+0200 [-] twistd 12.2.0 (/home/durand/projects/smk/products/dnssystem/site/venv/bin/python2.7 2.7.3) starting up.
2012-11-28 17:10:51+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2012-11-28 17:10:51+0200 [-] DNSServerFactory starting on 53000
2012-11-28 17:10:51+0200 [-] DNSDatagramProtocol starting on 53000
2012-11-28 17:10:51+0200 [-] /home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/python/util.py:713: exceptions.UserWarning: tried to drop privileges and setuid 1000 but uid is already 1000; should we be root? Continuing.
2012-11-28 17:10:51+0200 [-] set uid/gid 1000/100
2012-11-28 17:10:55+0200 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 54496
2012-11-28 17:10:55+0200 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x84c5aac>
2012-11-28 17:10:55+0200 [-] (UDP Port 54496 Closed)
2012-11-28 17:10:55+0200 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x84c5aac>
2012-11-28 17:10:59+0200 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 44947
2012-11-28 17:10:59+0200 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x84c58cc>
2012-11-28 17:10:59+0200 [-] (UDP Port 44947 Closed)
2012-11-28 17:10:59+0200 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x84c58cc>
2012-11-28 17:11:05+0200 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 52932
2012-11-28 17:11:05+0200 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x84c590c>
2012-11-28 17:11:05+0200 [-] (UDP Port 52932 Closed)
2012-11-28 17:11:05+0200 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x84c590c>
2012-11-28 17:24:35+0200 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 4547
2012-11-28 17:24:35+0200 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x84c5f0c>
2012-11-28 17:24:35+0200 [-] (UDP Port 4547 Closed)
2012-11-28 17:24:35+0200 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x84c5f0c>
2012-11-28 17:25:08+0200 [-] Received SIGTERM, shutting down.
2012-11-28 17:25:08+0200 [-] (UDP Port 53000 Closed)
2012-11-28 17:25:08+0200 [-] (TCP Port 53000 Closed)
2012-11-28 17:25:08+0200 [-] Main loop terminated.
2012-11-28 17:25:08+0200 [-] Server Shut Down.
2012-11-28 17:25:26+0200 [-] Log opened.
2012-11-28 17:25:26+0200 [-] twistd 12.2.0 (/home/durand/projects/smk/products/dnssystem/site/venv/bin/python2.7 2.7.3) starting up.
2012-11-28 17:25:26+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2012-11-28 17:25:26+0200 [-] DNSServerFactory starting on 53000
2012-11-28 17:25:26+0200 [-] DNSDatagramProtocol starting on 53000
2012-11-28 17:25:26+0200 [-] /home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/python/util.py:713: exceptions.UserWarning: tried to drop privileges and setuid 1000 but uid is already 1000; should we be root? Continuing.
2012-11-28 17:25:26+0200 [-] set uid/gid 1000/100
2012-11-28 17:25:29+0200 [DNSDatagramProtocol (UDP)] Unhandled Error
	Traceback (most recent call last):
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 68, in lookupAddress
	    return self._lookup(name, dns.IN, dns.A, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 48, in _lookup
	    FailureHandler(r.query, q, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 312, in addErrback
	    errbackKeywords=kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 290, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 551, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 29, in __call__
	    return self.resolver(self.query, self.timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 57, in query
	    return self.typeToMethod[query.type](str(query.name), timeout)
	  File "./server.py", line 26, in lookupAddress
	    result.addCallback(packResult) # put it in a A Record
	exceptions.AttributeError: 'str' object has no attribute 'addCallback'
	
2012-11-28 17:25:38+0200 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 8207
2012-11-28 17:25:38+0200 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x84c394c>
2012-11-28 17:25:38+0200 [-] (UDP Port 8207 Closed)
2012-11-28 17:25:38+0200 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x84c394c>
2012-11-28 17:25:46+0200 [DNSDatagramProtocol (UDP)] Unhandled Error
	Traceback (most recent call last):
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 68, in lookupAddress
	    return self._lookup(name, dns.IN, dns.A, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 48, in _lookup
	    FailureHandler(r.query, q, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 312, in addErrback
	    errbackKeywords=kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 290, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 551, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 29, in __call__
	    return self.resolver(self.query, self.timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 57, in query
	    return self.typeToMethod[query.type](str(query.name), timeout)
	  File "./server.py", line 26, in lookupAddress
	    result.addCallback(packResult) # put it in a A Record
	exceptions.AttributeError: 'str' object has no attribute 'addCallback'
	
2012-11-28 17:25:48+0200 [-] Received SIGTERM, shutting down.
2012-11-28 17:25:48+0200 [-] (UDP Port 53000 Closed)
2012-11-28 17:25:48+0200 [-] (TCP Port 53000 Closed)
2012-11-28 17:25:48+0200 [-] Main loop terminated.
2012-11-28 17:25:48+0200 [-] Server Shut Down.
2012-11-28 17:25:53+0200 [-] Log opened.
2012-11-28 17:25:53+0200 [-] twistd 12.2.0 (/home/durand/projects/smk/products/dnssystem/site/venv/bin/python2.7 2.7.3) starting up.
2012-11-28 17:25:53+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2012-11-28 17:25:53+0200 [-] DNSServerFactory starting on 53000
2012-11-28 17:25:53+0200 [-] DNSDatagramProtocol starting on 53000
2012-11-28 17:25:53+0200 [-] /home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/python/util.py:713: exceptions.UserWarning: tried to drop privileges and setuid 1000 but uid is already 1000; should we be root? Continuing.
2012-11-28 17:25:53+0200 [-] set uid/gid 1000/100
2012-11-28 17:25:58+0200 [DNSDatagramProtocol (UDP)] Unhandled Error
	Traceback (most recent call last):
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 68, in lookupAddress
	    return self._lookup(name, dns.IN, dns.A, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 48, in _lookup
	    FailureHandler(r.query, q, timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 312, in addErrback
	    errbackKeywords=kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 290, in addCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 551, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/resolve.py", line 29, in __call__
	    return self.resolver(self.query, self.timeout)
	  File "/home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/names/common.py", line 57, in query
	    return self.typeToMethod[query.type](str(query.name), timeout)
	  File "./server.py", line 26, in lookupAddress
	    result.addCallback(packResult) # put it in a A Record
	exceptions.AttributeError: 'str' object has no attribute 'addCallback'
	
2012-11-28 17:33:41+0200 [-] Received SIGTERM, shutting down.
2012-11-28 17:33:41+0200 [-] (UDP Port 53000 Closed)
2012-11-28 17:33:41+0200 [-] (TCP Port 53000 Closed)
2012-11-28 17:33:41+0200 [-] Main loop terminated.
2012-11-28 17:33:41+0200 [-] Server Shut Down.
2012-11-28 17:33:46+0200 [-] Log opened.
2012-11-28 17:33:46+0200 [-] twistd 12.2.0 (/home/durand/projects/smk/products/dnssystem/site/venv/bin/python2.7 2.7.3) starting up.
2012-11-28 17:33:46+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2012-11-28 17:33:46+0200 [-] DNSServerFactory starting on 53000
2012-11-28 17:33:46+0200 [-] DNSDatagramProtocol starting on 53000
2012-11-28 17:33:46+0200 [-] /home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/python/util.py:713: exceptions.UserWarning: tried to drop privileges and setuid 1000 but uid is already 1000; should we be root? Continuing.
2012-11-28 17:33:46+0200 [-] set uid/gid 1000/100
2012-11-28 17:33:49+0200 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 5062
2012-11-28 17:33:49+0200 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x84c3b4c>
2012-11-28 17:33:49+0200 [-] (UDP Port 5062 Closed)
2012-11-28 17:33:49+0200 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x84c3b4c>
2012-11-28 17:33:53+0200 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 31446
2012-11-28 17:33:53+0200 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x84c396c>
2012-11-28 17:33:54+0200 [-] (UDP Port 31446 Closed)
2012-11-28 17:33:54+0200 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x84c396c>
2012-11-28 17:35:56+0200 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 2245
2012-11-28 17:35:56+0200 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x84c39ac>
2012-11-28 17:35:56+0200 [-] (UDP Port 2245 Closed)
2012-11-28 17:35:56+0200 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x84c39ac>
2012-11-28 17:36:00+0200 [-] Received SIGTERM, shutting down.
2012-11-28 17:36:00+0200 [-] (UDP Port 53000 Closed)
2012-11-28 17:36:00+0200 [-] (TCP Port 53000 Closed)
2012-11-28 17:36:00+0200 [-] Main loop terminated.
2012-11-28 17:36:00+0200 [-] Server Shut Down.
2012-11-28 17:36:43+0200 [-] Log opened.
2012-11-28 17:36:43+0200 [-] twistd 12.2.0 (/home/durand/projects/smk/products/dnssystem/site/venv/bin/python2.7 2.7.3) starting up.
2012-11-28 17:36:43+0200 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2012-11-28 17:36:43+0200 [-] DNSServerFactory starting on 53000
2012-11-28 17:36:43+0200 [-] DNSDatagramProtocol starting on 53000
2012-11-28 17:36:43+0200 [-] /home/durand/projects/smk/products/dnssystem/site/venv/lib/python2.7/site-packages/twisted/python/util.py:713: exceptions.UserWarning: tried to drop privileges and setuid 1000 but uid is already 1000; should we be root? Continuing.
2012-11-28 17:36:43+0200 [-] set uid/gid 1000/100
2012-11-28 17:36:47+0200 [DNSDatagramProtocol (UDP)] Looking for www.google.com
2012-11-28 17:36:47+0200 [DNSDatagramProtocol (UDP)] DNSDatagramProtocol starting on 35242
2012-11-28 17:36:47+0200 [DNSDatagramProtocol (UDP)] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x84c3b4c>
2012-11-28 17:36:47+0200 [-] (UDP Port 35242 Closed)
2012-11-28 17:36:47+0200 [-] Stopping protocol <twisted.names.dns.DNSDatagramProtocol object at 0x84c3b4c>
2012-11-28 17:36:57+0200 [-] Received SIGTERM, shutting down.
2012-11-28 17:36:57+0200 [-] (UDP Port 53000 Closed)
2012-11-28 17:36:57+0200 [-] (TCP Port 53000 Closed)
2012-11-28 17:36:57+0200 [-] Main loop terminated.
2012-11-28 17:36:57+0200 [-] Server Shut Down.
